source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CustomSearchBar_Example', :exclusive => true do
  pod "CustomSearchBar", :path => "../"
end

target 'CustomSearchBar_Tests', :exclusive => true do
  pod "CustomSearchBar", :path => "../"

  
end
